name: audio_metadata_extractor
description: Extremely fast (Dart Language) and easy-to-use metadata extractor from mp3, m4a, m4bm, aac, mp4, flac audio files.
version: 0.0.4
repository: https://github.com/vadia/audio_metadata_extractor
homepage: https://github.com/vadia/audio_metadata_extractor

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  charset: ^2.0.1
  http: ^1.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
