import 'dart:convert';
import 'dart:typed_data';

import 'package:audio_metadata_extractor/src/id3_metadata/id3_context.dart';
import 'package:audio_metadata_extractor/src/id3_metadata/id3_geob.dart';
import 'package:audio_metadata_extractor/src/id3_metadata/utils.dart';
import 'package:test/test.dart';

void main() {
  test('id3 geob ...', () {
    var geobBase64 =
        "R0VPQgAAABkAAAAAAFNmTWFya2VycwAMAAAAZAAAAAAAAABHRU9CAAAAiAAAAAAAU2ZDREluZm8AHAAAAGQAAAABAAAAicaS0wbMx0y/Gw7FvmLwkxwAAABkAAAAicaS0wbMx0y/Gw7FvmLwk0QAAABEAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/+9IAAAAP/ABLgAAACKSACXAAAAEAAAEuAAAAIAAAJcAAAAQ=";
    var raw = base64.decode(geobBase64);

    String tagId;
    int size;
    int offset = 0;
    tagId = latin1.decode(Uint8List.view(raw.buffer, offset, 4));
    offset += 4;
    size = parseIntWithSync(raw, offset, false);
    offset += 4;
    offset += 2;
    var geob1 =
        ID3Geob(ID3Context(forceDuration: false), raw, tagId, offset, size);
    offset += size;
    expect(geob1.mimeType, "");
    expect(geob1.filename, "SfMarkers");
    expect(geob1.contentDescription, "");
    expect(geob1.objectOffset, 26);
    expect(geob1.objectLength, 9);

    tagId = latin1.decode(Uint8List.view(raw.buffer, offset, 4));
    offset += 4;
    size = parseIntWithSync(raw, offset, false);
    offset += 4;
    offset += 2;

    var geob2 =
        ID3Geob(ID3Context(forceDuration: false), raw, tagId, offset, size);
    expect(geob2.mimeType, "");
    expect(geob2.filename, "SfCDInfo");
    expect(geob2.contentDescription, "");
    expect(geob2.objectOffset, 60);
    expect(geob2.objectLength, 121);
  });
}
